name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build

      - name: Notificar Deploy Concluído
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *Deploy Concluído com Sucesso!*\n\n:rocket: *Site publicado:* https://fernando-da-costa.github.io/documentacao-geral/\n:octocat: *Repositório:* ${{ github.repository }}\n:calendar: *Data:* ${{ github.event.head_commit.timestamp }}\n:man: *Autor:* ${{ github.event.head_commit.author.name }}\n\n:link: *Acesse o site:* https://fernando-da-costa.github.io/documentacao-geral/"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notificar Falha no Deploy
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":x: *Falha no Deploy!*\n\n:warning: O deploy para GitHub Pages falhou.\n:octocat: *Repositório:* ${{ github.repository }}\n:calendar: *Data:* ${{ github.event.head_commit.timestamp }}\n:man: *Autor:* ${{ github.event.head_commit.author.name }}\n\n:link: *Ver logs:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
